server:
    port: 8088

eureka:
    instance:
        hostname: localhost
        port: 9000
    client:
        serviceUrl: 
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
            - id: AlunoModule
              uri: lb://AlunoService
              predicates:
              - Path=/aluno/**
            - id: ProfessorModule
              uri: lb://ProfessorService
              predicates:
              - Path=/professor/**
